### ISSUE TITLE
Multi Platform without NAudio or Windows.Forms Dependencies..

### ISSUE THREAD

**Issue by MiLO83** [RobertPeip/FPGBASharp#1]
Hi, I got FPGBASharp running without NAudio or Windows.Forms Dependencies..
https://drive.google.com/file/d/1dOY3lrFrkLinDRShnw_qh6DzrbM_TMj5/view?usp=sharing

I don't know how to get in touch with you to chat..
Can you email me @ simdiff @ gmail ? (.com)

Here is video of my recently completed project RxNES based on MyNES by Alaa Hadid :
I got MyNES v7 running in Unity3d and wrote the GFX enhancement routines.
I was hoping to do the same for FPGBASharp, but so far it runs too slow in Unity...
FrameSkip doesnt make it run faster on my PC, but disabling sound helps a lot.

Please Watch I hope you enjoy,
https://www.youtube.com/watch?v=HPZGHzET2WQ
https://www.youtube.com/watch?v=ZmZ__x_D1Dc

My name is Myles :) :)

**Comment by RobertPeip** [comment]
Hey, great to know somebody really uses this.

You can contact me here or via discord, e.g. in gbdev:
https://discordapp.com/invite/gpBxq85
or via skype.

Some things first:
There are some known bugs, the FPGA implementation doesn't have:
- CPU bugs -> crashes in some games
- GB Audio channels don't work correct and have wrong volume
- Mode 2 renderer has a rare bug, e.g. in colin mc rea racing

I didn't fix them yet, as my FPGA implementation doesn't have them and they don't hinder furhter development. However, if you really use it, i can fix them. 

For speed: what you show in the screenshot looks like a debug build. Those are significantly slower than release builds with optimization.

Also there are a lot of things that can be done to speed up the emulator. It will break the compatibility with my FPGA implementation, but that's not your main goal either.
We can work those out together.

bye, Robert

**Comment by MiLO83** [comment]
https://youtu.be/VGHmmGN5YA8

I know very little about ASM, however I think I would like to hook GBA ASM Routines...
For the GBA to render 3D models, I think this time rather than making a generic "don't need to get your hands dirty" approach, I would prefer to do something more for the technically educated.
Such as recognising ASM routines and operating off them in dynamic runtime compiled c# scripts.
I understand each game would need its own specific scripts, but I suppose someone could do the coding for a game that allowed other people to make the graphics..
What do you think?
I think the pop up book effect I tested in the youtube video above is kinda flaky.
I'm more into exposing C# in the Unity Game Engine to the GBA.
Using old logic where appropriate, but expanding into the new Engine / future hardware limits.
I aim to make the Games Refurbish-able.
While my next move is likely implementing the runtime c# compiler, I will also research GBA Disassembly before making any moves in any uninformed direction.
I think users could disassemble routines ect in other emulators if more proficient tools are standard, FPGBASharp would just have to recognize them and reinterpret / patch them in memory?
Do you have suggested learning material for me?
Even concepts currently above my own head could be implemented for use by the right people.
I simply think recognizing graphics is not the proper solution for a sequel to RxNES which hashes graphics and replaces them generically for all games.
How interested are you in refreshing these old games in Unity3D?
Of all the people online, i feel I am about most qualified to attempt it,
however your help and participation would be about critical.
I also wouldn't pursue the project using your code without your permission.
I typed all this with my mouse...
I'll check for your reply every 15 - 30 minutes if you wanna chat about feasibility and such.
    - Myles
Reusing old logic in new Engines.

**Comment by MiLO83** [comment]
I got the runtime c# compiler built into teh Unity version,
Attaching code from .cs documents.
Took about 5 hours.
This means other people can customize the Unity side of things with main script edits.
I don't think I can runtime compile the emu tho, just the unity interface.
later! - Myles

**Comment by RobertPeip** [comment]
I have seen you are in the gb dev discord, so i sen't you a message there. It's better for chatting.
